name = "ChargedParticles"
uuid = "0eb1dcc5-379a-4d99-9f08-a5c692c046ba"
authors = ["Pranay Venkatesh"]
version = "1.0.0-DEV"

[deps]
Gnuplot = "dc211083-a33a-5b79-959f-2ff34033469d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
